package dev.space.view.panel;

import dev.space.dto.JournalistDTO;
import dev.space.factory.MapperFactory;
import dev.space.model.Journalist;
import dev.space.model.JournalistTableModel;
import dev.space.query.operation.JournalistOperations;
import dev.space.session.HibernateSessionFactory;
import dev.space.session.Operations;
import dev.space.utilities.MessageUtils;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.ListSelectionModel;
import javax.swing.text.JTextComponent;
import org.modelmapper.ModelMapper;

/**
 *
 * @author tomislav
 */
public class ManageJournalistsPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageCategoriesPanel
     */
    public ManageJournalistsPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbJournalist = new javax.swing.JTable();
        lbCategoryType = new javax.swing.JLabel();
        tfFirstName = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        lbFirstError = new javax.swing.JLabel();
        tfLastName = new javax.swing.JTextField();
        lbCategoryType1 = new javax.swing.JLabel();
        lbLastError = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(1280, 689));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        tbJournalist.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbJournalist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbJournalistMouseClicked(evt);
            }
        });
        tbJournalist.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tbJournalistKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tbJournalist);

        lbCategoryType.setText("First Name:");

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnUpdate.setText("Edit");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        lbFirstError.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        lbFirstError.setForeground(new java.awt.Color(255, 0, 0));
        lbFirstError.setText("X");

        lbCategoryType1.setText("Last Name:");

        lbLastError.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        lbLastError.setForeground(new java.awt.Color(255, 0, 0));
        lbLastError.setText("X");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tfFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbFirstError))
                    .addComponent(lbCategoryType, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tfLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbLastError))
                    .addComponent(lbCategoryType1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 612, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 689, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(lbCategoryType, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbFirstError))
                .addGap(18, 18, 18)
                .addComponent(lbCategoryType1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbLastError))
                .addGap(99, 99, 99)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        initialize();
    }//GEN-LAST:event_formComponentShown

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        if (!formValid()) {
            return;
        }

        try {
            JournalistDTO journalist = new JournalistDTO(
                    tfFirstName.getText().trim(),
                    tfLastName.getText().trim()
            );

            journalistSession.InsertEntity(mapper.map(journalist, Journalist.class));

            refreshTable();
            clearForm();
        } catch (Exception ex) {
            MessageUtils.showErrorMessage("Error", ex.getMessage());
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        if (selectedJournalist == null) {
            MessageUtils.showInformationMessage("Incorrect operations", "You must select journalist before deleting");
            return;
        }

        if (!formValid()) {
            return;
        }

        try {
            JournalistDTO journalist = new JournalistDTO(
                    selectedJournalist.getIdJournalist(),
                    tfFirstName.getText().trim(),
                    tfLastName.getText().trim()
            );

            Journalist map = mapper.map(journalist, Journalist.class);

            journalistSession.UpdateEntity(map);

            refreshTable();
            clearForm();
        } catch (Exception ex) {
            MessageUtils.showErrorMessage("Error", ex.getMessage());
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        if (selectedJournalist == null) {
            MessageUtils.showInformationMessage("Incorrect operations", "You must select journalist before deleting");
            return;
        }

        if (MessageUtils.showConfirmDialog(
                "Delete article",
                "Do you really want to delete article?")) {
            try {
                journalistSession.DeleteEntity(selectedJournalist.getIdJournalist());

                journalistTableModel.setJournalists(journalistSession.ReadAllEntities().get());

                clearForm();
            } catch (Exception ex) {
                MessageUtils.showErrorMessage("Error", ex.getMessage());
            }

        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void tbJournalistKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbJournalistKeyReleased
        try {
            showJournalist();
        } catch (Exception ex) {
            MessageUtils.showErrorMessage("Error", ex.getMessage());
        }
    }//GEN-LAST:event_tbJournalistKeyReleased

    private void tbJournalistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbJournalistMouseClicked
        try {
            showJournalist();
        } catch (Exception ex) {
            MessageUtils.showErrorMessage("Error", ex.getMessage());
        }
    }//GEN-LAST:event_tbJournalistMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbCategoryType;
    private javax.swing.JLabel lbCategoryType1;
    private javax.swing.JLabel lbFirstError;
    private javax.swing.JLabel lbLastError;
    private javax.swing.JTable tbJournalist;
    private javax.swing.JTextField tfFirstName;
    private javax.swing.JTextField tfLastName;
    // End of variables declaration//GEN-END:variables

    private JournalistTableModel journalistTableModel;

    private JournalistOperations journalistSession;

    private Map<JTextComponent, JLabel> fields = new HashMap<>();

    private ModelMapper mapper;

    private Journalist selectedJournalist;

    private void initialize() {
        try {
            initValidation();
            hideErrors();
            initMapper();
            initSession();
            initTable();
        } catch (Exception ex) {
            Logger.getLogger(ManageJournalistsPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void initValidation() {
        fields.put(tfFirstName, lbFirstError);
        fields.put(tfLastName, lbLastError);
    }

    private void hideErrors() {
        fields.entrySet().forEach(e -> {
            e.getValue().setVisible(false);
        });
    }

    private void initMapper() {
        mapper = MapperFactory.InitializeMapper();
    }

    private void initSession() {
        journalistSession = HibernateSessionFactory.InitializeSession(Operations.JOURNALIST);
    }

    private void initTable() throws Exception {
        tbJournalist.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tbJournalist.setAutoCreateRowSorter(true);
        tbJournalist.setRowHeight(25);

        journalistTableModel = new JournalistTableModel(journalistSession.ReadAllEntities().get());

        tbJournalist.setModel(journalistTableModel);
    }

    private void clearForm() {
        selectedJournalist = null;

        fields.entrySet().forEach(entry -> {
            entry.getKey().setText("");
        });
    }

    private void refreshTable() throws Exception {
        journalistTableModel = new JournalistTableModel(journalistSession.ReadAllEntities().get());
        tbJournalist.setModel(journalistTableModel);
    }

    private boolean formValid() {
        boolean ok = true;

        for (Map.Entry<JTextComponent, JLabel> entry : fields.entrySet()) {
            ok &= !entry.getKey().getText().trim().isEmpty();
            entry.getValue().setVisible(entry.getKey().getText().trim().isEmpty());
        }

        return ok;
    }

    private void showJournalist() throws Exception {
        int selectedRow = tbJournalist.getSelectedRow();
        int rowIndex = tbJournalist.convertRowIndexToModel(selectedRow);

        int id = (int) journalistTableModel.getValueAt(rowIndex, 0);
        selectedJournalist = journalistSession.ReadEntityById(id).get();
        fillForm(selectedJournalist);
    }

    private void fillForm(Journalist selectedCategory) {
        tfFirstName.setText(selectedCategory.getFirstName());
        tfLastName.setText(selectedCategory.getLastName());
    }
}
